# Created by Yanjunhui
# Analysis options for MonoLite Dart library

analyzer:
  errors:
    unused_field: warning
    unused_local_variable: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
